/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kyh.tam;

public class ClientApp {
  public static void main(String[] args) {
    System.out.println("TAM Client");
  }
}
