/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kyh.tam;

import org.junit.Test;

public class ServerAppTest {
  @Test
  public void testAppHasAGreeting() {
    // ServerApp classUnderTest = new ServerApp();
    // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }
}
